-- QuickLook keybind snippet for Omarchy / Hyprland.
-- Default: SUPER + PERIOD (.). Alternate: SUPER + ALT + PERIOD.
-- Super+Shift+P is stock Google Photos — never steal it.
--
-- The overlay first-run card can write a marked o.bind block via
-- `omarchy-shell io.github.chris.quicklook installBinds ''`.
-- Paste these lines only if you prefer to bind by hand.
--
--   o.bind("SUPER + PERIOD", "QuickLook", "omarchy-shell shell toggle io.github.chris.quicklook '{}'")
--   o.bind("SUPER + ALT + PERIOD", "QuickLook", "omarchy-shell shell toggle io.github.chris.quicklook '{}'")
--
-- Hyprland:
--   bind = SUPER, period, exec, omarchy-shell shell toggle io.github.chris.quicklook '{}'
--   bind = SUPER ALT, period, exec, omarchy-shell shell toggle io.github.chris.quicklook '{}'
-- File manager custom action:
--   omarchy-shell shell summon io.github.chris.quicklook '{"path":"%f"}'
